# Numpy
----

In [7]:
import numpy as np

### np.array

In [5]:
myList = [1, 2, 3]
type(np.array(myList))

numpy.ndarray

In [6]:
np.array(myList)

array([1, 2, 3])

### np.arange

In [10]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1, 11, 3)

array([ 1,  4,  7, 10])

### np.zeros

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.ones

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### np.linspace

In [16]:
np.linspace(0, 11, 15)

array([ 0.        ,  0.78571429,  1.57142857,  2.35714286,  3.14285714,
        3.92857143,  4.71428571,  5.5       ,  6.28571429,  7.07142857,
        7.85714286,  8.64285714,  9.42857143, 10.21428571, 11.        ])

### np.random.randint

In [18]:
np.random.randint(0, 10)

3

In [19]:
np.random.randint(0, 100, (3, 5))

array([[79,  4, 44,  1, 32],
       [47,  4, 71, 48, 31],
       [30, 18, 61, 76, 24]])

### np.random.normal

In [31]:
np.random.normal()

-1.0425459508946786

In [34]:
np.random.normal((10,10000000, 545))

array([9.80813647e+00, 9.99999875e+06, 5.44756299e+02])

### np.random.seed

In [35]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [36]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [37]:
np.random.randint(0, 100, 10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

### operators

In [40]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [41]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [39]:
arr.max()

95

In [42]:
arr.min()

9

In [43]:
arr.mean()

60.8

In [44]:
arr.argmax()

0

In [45]:
arr.argmin()

7

### np.reshape

In [47]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [48]:
mat = np.arange(0,100).reshape(10,10)

In [49]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Grap value

In [50]:
mat[0,1]

1

In [51]:
mat[4,3]

43

In [52]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [54]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

### Masking

In [55]:
myFilter = mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])