# SciKit-Learn Preprocessing
----

In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [12]:
data = np.random.randint(0, 100, (10, 2))
data

array([[60, 99],
       [ 9, 78],
       [97, 64],
       [93, 74],
       [ 5, 21],
       [13, 16],
       [41, 39],
       [50,  6],
       [62, 45],
       [ 9, 25]])

### MinMaxScaler

In [6]:
scalerModel = MinMaxScaler()
type(scalerModel)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scalerModel.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scalerModel.transform(data)

array([[0.45555556, 0.47368421],
       [0.44444444, 0.01052632],
       [0.56666667, 0.23157895],
       [1.        , 0.        ],
       [0.        , 0.28421053],
       [0.78888889, 1.        ],
       [0.85555556, 0.23157895],
       [0.15555556, 0.47368421],
       [0.38888889, 0.29473684],
       [0.44444444, 0.46315789]])

In [10]:
scalerModel.fit_transform(data)

array([[0.45555556, 0.47368421],
       [0.44444444, 0.01052632],
       [0.56666667, 0.23157895],
       [1.        , 0.        ],
       [0.        , 0.28421053],
       [0.78888889, 1.        ],
       [0.85555556, 0.23157895],
       [0.15555556, 0.47368421],
       [0.38888889, 0.29473684],
       [0.44444444, 0.46315789]])

### Sample with Pandas

In [15]:
import pandas as pd

In [25]:
myDatas = np.random.randint(0, 101, (50, 4))
df = pd.DataFrame(data=myDatas, columns=['f1', 'f2', 'f3', 'label'])
df.head()

f1  f2  f3  label
0  53  21  37     88
1  57  26  96     92
2   2  26  93     62
3  45  18  17      6
4   0  63  26     23

### Split Train and Test datas

In [18]:
x = df[['f1', 'f2', 'f3']]
y = df['label']

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.3, random_state=101)

In [24]:
f'X-Train: {xTrain.shape}, X-Test: {xTest.shape}, Y-Train: {yTrain.shape}, Y-Test: {yTest.shape}'

'X-Train: (35, 3), X-Test: (15, 3), Y-Train: (35,), Y-Test: (15,)'